# Renders the recipient policy from `flake.safix.users` and
# `flake.safix.catalogue`, as a pure function of those two records, so the policy
# the sops CLI reads off disk and the audiences the resolver computes are two
# projections of one declaration rather than two lists that agree by inspection.
#
# The sops CLI reads `.sops.yaml` from the filesystem, not from a nix evaluation,
# so the file has to stay committed in the consumer's repository. `plan` is the
# structured contract — anchors, and one rule per audience — and `renderPlan` is
# the text. They are split because a check that asserts the whole rendered file
# against a literal fails on every prose edit, whereas the plan is exactly what a
# reader would want held: which key each anchor names, and which anchors each
# rule grants.
#
# Deliberately not a script that rewrites the file from a template. A template
# does not know the people, so a per-person rule survives only until the next
# run. Here the people are the input.
{ lib }:
let
  resolve = import ./resolve.nix { inherit lib; };

  sortNames = lib.sort (a: b: a < b);

  commentLines =
    indent: text:
    lib.concatMapStrings (l: "${indent}#${lib.optionalString (l != "") " "}${l}\n") (
      lib.splitString "\n" (lib.removeSuffix "\n" text)
    );

  # The command a reader is sent to when this file and the declarations disagree.
  # Named once, so the header, the drift check's failure, and anything else that
  # has to say it cannot drift apart from each other.
  regenerateCommand = "safix fix";

  header = ''
    .sops.yaml — generated by safix. Do not edit by hand.

    Regenerate with `${regenerateCommand}`, which writes this file and then
    re-wraps each governed file's data key to the audience it declares. The
    policy-drift check fails while the committed file and the generated one
    differ, and its failure names that command. Its whole input is
    flake.safix.users — each person's `recipient`, their `recoveryRecipients`,
    and the secrets they own and share under `carries`, `private` and
    `sharedWith` — together with flake.safix.catalogue.

    ── one rule per audience ──
    A sops file has a single data key, wrapped once per recipient, so anyone who
    can open the file opens every value in it. Recipients are a property of the
    file and never of a key inside it. Sharing two of ten values therefore splits
    by audience into separate files: a secret's audience is its owner plus
    everyone the owner shares it with, each distinct audience gets one file, and
    each file gets one rule naming exactly that audience's recipients.

    A person's own secrets keep their own directory. A shared audience gets
    secrets/safix/shared/<a>,<b>/, named for its members in sorted order so the
    path states who can open it without opening it. The separator is one the name
    alphabet excludes, which is what keeps two audiences from reaching one
    directory and so one rule.

    ── anchoring is load-bearing ──
    Anchoring survives every edit to the generator, in two independent ways:

      1. Every `path_regex` ends in a literal `\.yaml$`. A rule that did not
         terminate on the extension would match encrypted material safix did not
         place, and a `sops updatekeys` sweep would then silently rewrite that
         material's recipients — unrecoverable without the original identities.
      2. Every `path_regex` is anchored with `^`. sops matches `path_regex`
         unanchored against the path relative to this file's directory, so an
         unanchored rule also matches the same suffix under any prefix:
         `nested/secrets/safix/users/ana/x.yaml` would match a rule written for
         `secrets/safix/users/ana/`. `[^/]*` rather than `.*` keeps each rule to
         one directory level, so a file dropped in a subdirectory fails closed
         instead of silently inheriting a person's recipients. It is `[^/]*`
         rather than one literal filename so that a file placed beside a person's
         secrets rides the same custody instead of being stranded with no rule at
         all.

    There is deliberately no catch-all rule, and the generator emits none. An
    unmatched path must fail closed with "no matching creation rules found"
    rather than silently acquiring a default recipient set. A new person means a
    new flake.safix.users entry with a recipient, which is what produces their
    rule.

    ── revocation is not retroactive ──
    Narrowing an audience — dropping a grant, clearing a recipient — stops future
    encryptions reaching that person and regenerates this file accordingly. It
    takes nothing back: they have already read every value in every file they
    could open, and only minting a new value revokes it.

    Nor can rotation happen on revoke. An evaluation sees only the audience that
    is declared, never the audience that used to be, so no rebuild can detect a
    removal. `${regenerateCommand}` re-wraps each file's data key to the audience
    declared here, which aligns ciphertext with policy and is not revocation;
    revoking is a new value, which is `safix generate --regenerate <user> <name>`
    or `sops <file>`.
  '';

  # Registry-wide anchor order: recovery identities first, sorted by anchor, then
  # one `<user>-safix` per person that records a recipient, sorted by user. Rule
  # bodies are emitted in this order too, so a rule's recipient list reads the
  # same way the keys block does.
  anchorsOf =
    users:
    let
      recovery = lib.concatMap (
        user:
        lib.mapAttrsToList (anchor: r: {
          inherit anchor;
          inherit (r) key note;
        }) users.${user}.recoveryRecipients
      ) (sortNames (builtins.attrNames users));

      deduped = lib.mapAttrsToList (_anchor: defs: builtins.head defs) (
        lib.groupBy (d: d.anchor) recovery
      );

      primary = map (user: {
        anchor = "${user}-safix";
        key = users.${user}.recipient;
        note = users.${user}.recipientNote;
      }) (sortNames (builtins.attrNames (lib.filterAttrs (_n: u: u.recipient != null) users)));
    in
    lib.sort (a: b: a.anchor < b.anchor) deduped ++ primary;

  audienceNote =
    audience:
    if builtins.length audience == 1 then
      "Audience: ${builtins.head audience} alone — their own custody. The recipients\n"
      + "below are the identities that one person holds."
    else
      "Audience: ${lib.concatStringsSep ", " audience}.\n"
      + "One data key, wrapped once per recipient, so every member of this audience\n"
      + "opens every value in this directory. That is why sharing lands here rather\n"
      + "than adding a recipient to one of their personal files.";

  plan =
    users: catalogue:
    let
      anchors = anchorsOf users;
      anchorOfKey = lib.listToAttrs (map (a: lib.nameValuePair a.key a.anchor) anchors);
      order = lib.imap0 (i: a: lib.nameValuePair a.anchor i) anchors;
      rankOf = lib.listToAttrs order;

      audiences = resolve.audiencesOf users catalogue;
    in
    {
      inherit anchors;
      rules = lib.sort (a: b: a.pathRegex < b.pathRegex) (
        lib.mapAttrsToList (_file: a: {
          pathRegex = "^${a.dir}/[^/]*\\.yaml$";
          inherit (a) audience;
          anchors = lib.sort (x: y: rankOf.${x} < rankOf.${y}) (map (k: anchorOfKey.${k}) a.recipients);
        }) audiences
      );
    };

  renderPlan =
    p:
    commentLines "" header
    + "\nkeys:\n"
    + lib.concatMapStrings (
      a: lib.optionalString (a.note != null) (commentLines "  " a.note) + "  - &${a.anchor} ${a.key}\n"
    ) p.anchors
    + "\ncreation_rules:\n"
    + lib.concatStringsSep "\n" (
      map (
        r:
        commentLines "  " (audienceNote r.audience)
        + "  - path_regex: ${r.pathRegex}\n"
        + "    key_groups:\n"
        + "      - age:\n"
        + lib.concatMapStrings (a: "          - *${a}\n") r.anchors
      ) p.rules
    );

  render = users: catalogue: renderPlan (plan users catalogue);

  # What a consumer's drift check says when the committed policy and the
  # generated one disagree. A named string rather than prose inlined in a
  # builder, so that the sentence naming the regenerating command can be asserted
  # by a check instead of being trusted to stay in step with the header.
  driftMessage = ''
    The committed .sops.yaml differs from the one safix generates. The sops CLI
    reads the committed file, so that is the version deciding what a new file is
    encrypted to.

    Regenerate and commit it:  ${regenerateCommand}

    If the committed side is the one you meant, the change belongs in
    flake.safix.users.<u>.recipient, .recoveryRecipients or .sharedWith, not in
    the generated file.
  '';

  # The check that holds a consumer's committed policy to the generated one.
  # Built here rather than in the consumer's tree so that the failure and the
  # header name one command.
  mkDriftCheck =
    pkgs:
    {
      committed,
      generated,
    }:
    pkgs.runCommand "safix-policy-drift"
      {
        committedText = builtins.unsafeDiscardStringContext (builtins.readFile committed);
        generatedText = generated;
        passAsFile = [
          "committedText"
          "generatedText"
        ];
        meta.description = "structural check: safix-policy-drift";
      }
      ''
        if ! diff -u "$committedTextPath" "$generatedTextPath"; then
          cat >&2 <<'SAFIX_DRIFT'
        ${driftMessage}
        SAFIX_DRIFT
          exit 1
        fi
        touch "$out"
      '';
in
{
  inherit
    plan
    renderPlan
    render
    driftMessage
    mkDriftCheck
    regenerateCommand
    ;
}
